# Generated by Django 4.2.7 on 2023-11-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0003_alter_noticia_imagen_alter_recomendacion_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiquetas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="noticia",
            name="etiquetas",
            field=models.ManyToManyField(blank=True, null=True, to="inicio.etiquetas"),
        ),
    ]
