# Generated by Django 4.2.7 on 2023-11-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profesionales", "0001_initial"),
        ("turnos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turno",
            name="horario",
        ),
        migrations.RemoveField(
            model_name="turno",
            name="persona",
        ),
        migrations.AddField(
            model_name="turno",
            name="profesional",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="profesionales.profesional",
            ),
            preserve_default=False,
        ),
    ]
