# Generated by Django 4.2.7 on 2023-11-14 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_persona_apellido_alter_persona_dni_and_more"),
        ("turnos", "0002_remove_turno_horario_remove_turno_persona_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turno",
            name="persona",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="usuarios.persona",
            ),
            preserve_default=False,
        ),
    ]
