# Generated by Django 4.2.7 on 2023-11-15 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0002_alter_persona_apellido_alter_persona_dni_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="email",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="nombre",
        ),
        migrations.AddField(
            model_name="persona",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
